spring:
  application:
    name: "configserver"

  profiles:
    active: git
  cloud:
    config:
      server:
        native:
          #search-locations: "classpath:/config"
          #search-locations: "F:\\Workspace\\Yogesh\\microservices\\configserver\\src\\main\\resources\\config"
        git:
          uri: "https://github.com/yogeshukale07/bank-config-properties.git"
          username: yogeshukale07
          password: Yu$99222
          default-label: master
          timeout: 5
          clone-on-start: true
          force-pull: true
encrypt:
  key: "Yogesh"

server:
  port: 8071

